---
title: "Micro-grid data analysis (Aug 2019)"
output:
  html_document:
    df_print: paged
  fig_caption: yes
  pdf_document: default
---

```{r, echo=FALSE, include = FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=7) 
```

This report contains analysis of data obtained from the microgrid installed at Kigeme for the month of Aug 2019. There are a total of 20 CPE and 10 sockets - 6 CPE and 4 sockets in Nursery 1, 6 CPE and 4 sockets in Nursery 2, 5 CPE and 2 sockets in the playground and 3 CPE for the streetlights.

```{r, echo=FALSE, include=FALSE}
library(ggplot2)
library(dplyr)
library(lubridate)
library(readxl)
library(tidyverse)
library(stringr)
library(rlang)
library(readr)
```

```{r, echo=FALSE, include=FALSE}
#Extract hourly means for LED[1,2,3]_P values (mW) from the CPE1-CPE20 files and convert to W
cpe1 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 1A CPE1/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe1 <- rbind(cpe1, df)
  }
}
cpe1$id <- rep("Nur1A_CPE1", length(cpe1$value))

cpe2 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 1A CPE2/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe2 <- rbind(cpe2, df)
  }
}
cpe2$id <- rep("Nur1A_CPE2", length(cpe2$value))

cpe3 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 1B CPE3/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe3 <- rbind(cpe3, df)
  }
}
cpe3$id <- rep("Nur1B_CPE3", length(cpe3$value))

cpe4 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 1B CPE4/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe4 <- rbind(cpe4, df)
  }
}
cpe4$id <- rep("Nur1B_CPE4", length(cpe4$value))

cpe5 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 1C CPE5/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe5 <- rbind(cpe5, df)
  }
}
cpe5$id <- rep("Nur1C_CPE5", length(cpe5$value))

cpe6 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 1C CPE6/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe6 <- rbind(cpe6, df)
  }
}
cpe6$id <- rep("Nur1C_CPE6", length(cpe6$value))

cpe7 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 2A CPE7/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe7 <- rbind(cpe7, df)
  }
}
cpe7$id <- rep("Nur2A_CPE7", length(cpe7$value))

cpe8 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 2A CPE8/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe8 <- rbind(cpe8, df)
  }
}
cpe8$id <- rep("Nur2A_CPE8", length(cpe8$value))

cpe9 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 2B CPE9/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe9 <- rbind(cpe9, df)
  }
}
cpe9$id <- rep("Nur2B_CPE9", length(cpe9$value))

cpe10 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 2B CPE10/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe10 <- rbind(cpe10, df)
  }
}
cpe10$id <- rep("Nur2B_CPE10", length(cpe10$value))

cpe11 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 2C CPE11/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe11 <- rbind(cpe11, df)
  }
}
cpe11$id <- rep("Nur2C_CPE11", length(cpe11$value))

cpe12 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 2C CPE12/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe12 <- rbind(cpe12, df)
  }
}
cpe12$id <- rep("Nur2C_CPE12", length(cpe12$value))

cpe13 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Playground CPE1/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe13 <- rbind(cpe13, df)
  }
}
cpe13$id <- rep("PG_CPE1", length(cpe13$value))

cpe14 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Playground CPE2/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe14 <- rbind(cpe14, df)
  }
}
cpe14$id <- rep("PG_CPE2", length(cpe14$value))

cpe15 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Playground CPE3/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe15 <- rbind(cpe15, df)
  }
}
cpe15$id <- rep("PG_CPE3", length(cpe15$value))

cpe16 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Playground CPE4/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe16 <- rbind(cpe16, df)
  }
}
cpe16$id <- rep("PG_CPE4", length(cpe16$value))

cpe17 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Playground CPE5/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe17 <- rbind(cpe17, df)
  }
}
cpe17$id <- rep("PG_CPE5", length(cpe17$value))

cpe18 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Streetlight 1 CPE/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe18 <- rbind(cpe18, df)
  }
}
cpe18$id <- rep("SL_CPE1", length(cpe18$value))

cpe19 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Streetlight 2 CPE/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe19 <- rbind(cpe19, df)
  }
}
cpe19$id <- rep("SL_CPE2", length(cpe19$value))

cpe20 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Streetlight 3 CPE/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption variables only
    df_sub <- df[df$variable=="LED1_P" | df$variable=="LED2_P" | df$variable=="LED3_P",]
    df_sub$value <- as.numeric(df_sub$value)/1000.0 #Converting to W
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for each variable - led1_p, led2_p, led3_p
    df2 <- df_sub %>%
      group_by(variable, timeUse) %>%
      summarise(value = mean(value))
    
    #Add date from the file name
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    cpe20 <- rbind(cpe20, df)
  }
}
cpe20$id <- rep("SL_CPE3", length(cpe20$value))
```

```{r, echo=FALSE}
#Extract hourly mean for vRELAY1_VL (W) and hourly total for AC_Day_Energy_session (Wm) values from S1-S10 files 
s1 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 1A S1/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption (vRELAY1_LVL in W) and cumulative energy (AC_Day_Energy_session in Wattmin)
    df_sub <- df[df$variable=="vRELAY1_LVL" | df$variable=="AC_Day_Energy_session", ]
    df_sub$value <- as.numeric(df_sub$value)
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for instantaneous power
    df2 <- df_sub[df_sub$variable=="vRELAY1_LVL",] %>%
      group_by(timeUse) %>%
      summarise(value = mean(value))
    df2$variable <-rep("vRELAY1_LVL", length(df2$timeUse))
    
    #Correct cumulative total energy if not reset
    df3_sub <- df_sub[df_sub$variable=="AC_Day_Energy_session", ]
    if(df3_sub$value[1]!=0) { #If value has not reset
      #find if and where the value has reset
      flag=FALSE
      for(l in 2:length(df3_sub$timestamp)) {
        if(flag==FALSE & df3_sub$value[l] < df3_sub$value[l-1]) {
          flag=TRUE
          index <- l
        }
      }
      if(flag==FALSE) { #Means the value never reset to 0
        #Subtract value at 0th index from all values
        df3_sub$value2 <- df3_sub$value - df3_sub$value[1]
      } else {
        df3_sub$value2 <- df3_sub$value
        df3_sub$value2[1:(index-1)] <- (df3_sub$value[1:(index-1)] - df3_sub$value[1])
        df3_sub$value2[index:length(df3_sub$timestamp)] <- 
          df3_sub$value[index:length(df3_sub$timestamp)] + df3_sub$value2[index-1]
      }
    } else {
      df3_sub$value2 <- df3_sub$value
    }
    
    #Extract cumulative total energy per hour
    df3 <- df3_sub %>%
      group_by(timeUse) %>%
      summarise(value = value2[length(value2)])
    df3$variable <-rep("AC_Day_Energy_session", length(df3$timeUse))
    
    #Bind the 2 data frames and add date from the file name
    df2 <- rbind(df2, df3)
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    s1 <- rbind(s1, df)
  }
}
s1$id <- rep("Nur1A_S1", length(s1$value))

s2 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 1A S2/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption (vRELAY1_LVL in W) and cumulative energy (AC_Day_Energy_session in Wattmin)
    df_sub <- df[df$variable=="vRELAY1_LVL" | df$variable=="AC_Day_Energy_session", ]
    df_sub$value <- as.numeric(df_sub$value)
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for instantaneous power
    df2 <- df_sub[df_sub$variable=="vRELAY1_LVL",] %>%
      group_by(timeUse) %>%
      summarise(value = mean(value))
    df2$variable <-rep("vRELAY1_LVL", length(df2$timeUse))
    
    #Correct cumulative total energy if not reset
    df3_sub <- df_sub[df_sub$variable=="AC_Day_Energy_session", ]
    if(df3_sub$value[1]!=0) { #If value has not reset
      #find if and where the value has reset
      flag=FALSE
      for(l in 2:length(df3_sub$timestamp)) {
        if(flag==FALSE & df3_sub$value[l] < df3_sub$value[l-1]) {
          flag=TRUE
          index <- l
        }
      }
      if(flag==FALSE) { #Means the value never reset to 0
        #Subtract value at 0th index from all values
        df3_sub$value2 <- df3_sub$value - df3_sub$value[1]
      } else {
        df3_sub$value2 <- df3_sub$value
        df3_sub$value2[1:(index-1)] <- (df3_sub$value[1:(index-1)] - df3_sub$value[1])
        df3_sub$value2[index:length(df3_sub$timestamp)] <- 
          df3_sub$value[index:length(df3_sub$timestamp)] + df3_sub$value2[index-1]
      }
    } else {
      df3_sub$value2 <- df3_sub$value
    }
    
    #Extract cumulative total energy per hour
    df3 <- df3_sub %>%
      group_by(timeUse) %>%
      summarise(value = value2[length(value2)])
    df3$variable <-rep("AC_Day_Energy_session", length(df3$timeUse))
    
    #Bind the 2 data frames and add date from the file name
    df2 <- rbind(df2, df3)
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    s2 <- rbind(s2, df)
  }
}
s2$id <- rep("Nur1A_S2", length(s2$value))

s3 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 1B S1/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption (vRELAY1_LVL in W) and cumulative energy (AC_Day_Energy_session in Wattmin)
    df_sub <- df[df$variable=="vRELAY1_LVL" | df$variable=="AC_Day_Energy_session", ]
    df_sub$value <- as.numeric(df_sub$value)
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for instantaneous power
    df2 <- df_sub[df_sub$variable=="vRELAY1_LVL",] %>%
      group_by(timeUse) %>%
      summarise(value = mean(value))
    df2$variable <-rep("vRELAY1_LVL", length(df2$timeUse))
    
    #Correct cumulative total energy if not reset
    df3_sub <- df_sub[df_sub$variable=="AC_Day_Energy_session", ]
    if(df3_sub$value[1]!=0) { #If value has not reset
      #find if and where the value has reset
      flag=FALSE
      for(l in 2:length(df3_sub$timestamp)) {
        if(flag==FALSE & df3_sub$value[l] < df3_sub$value[l-1]) {
          flag=TRUE
          index <- l
        }
      }
      if(flag==FALSE) { #Means the value never reset to 0
        #Subtract value at 0th index from all values
        df3_sub$value2 <- df3_sub$value - df3_sub$value[1]
      } else {
        df3_sub$value2 <- df3_sub$value
        df3_sub$value2[1:(index-1)] <- (df3_sub$value[1:(index-1)] - df3_sub$value[1])
        df3_sub$value2[index:length(df3_sub$timestamp)] <- 
          df3_sub$value[index:length(df3_sub$timestamp)] + df3_sub$value2[index-1]
      }
    } else {
      df3_sub$value2 <- df3_sub$value
    }
    
    #Extract cumulative total energy per hour
    df3 <- df3_sub %>%
      group_by(timeUse) %>%
      summarise(value = value2[length(value2)])
    df3$variable <-rep("AC_Day_Energy_session", length(df3$timeUse))
    
    #Bind the 2 data frames and add date from the file name
    df2 <- rbind(df2, df3)
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    s3 <- rbind(s3, df)
  }
}
s3$id <- rep("Nur1B_S1", length(s3$value))

s4 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 1C S1/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption (vRELAY1_LVL in W) and cumulative energy (AC_Day_Energy_session in Wattmin)
    df_sub <- df[df$variable=="vRELAY1_LVL" | df$variable=="AC_Day_Energy_session", ]
    df_sub$value <- as.numeric(df_sub$value)
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for instantaneous power
    df2 <- df_sub[df_sub$variable=="vRELAY1_LVL",] %>%
      group_by(timeUse) %>%
      summarise(value = mean(value))
    df2$variable <-rep("vRELAY1_LVL", length(df2$timeUse))
    
    #Correct cumulative total energy if not reset
    df3_sub <- df_sub[df_sub$variable=="AC_Day_Energy_session", ]
    if(df3_sub$value[1]!=0) { #If value has not reset
      #find if and where the value has reset
      flag=FALSE
      for(l in 2:length(df3_sub$timestamp)) {
        if(flag==FALSE & df3_sub$value[l] < df3_sub$value[l-1]) {
          flag=TRUE
          index <- l
        }
      }
      if(flag==FALSE) { #Means the value never reset to 0
        #Subtract value at 0th index from all values
        df3_sub$value2 <- df3_sub$value - df3_sub$value[1]
      } else {
        df3_sub$value2 <- df3_sub$value
        df3_sub$value2[1:(index-1)] <- (df3_sub$value[1:(index-1)] - df3_sub$value[1])
        df3_sub$value2[index:length(df3_sub$timestamp)] <- 
          df3_sub$value[index:length(df3_sub$timestamp)] + df3_sub$value2[index-1]
      }
    } else {
      df3_sub$value2 <- df3_sub$value
    }
    
    #Extract cumulative total energy per hour
    df3 <- df3_sub %>%
      group_by(timeUse) %>%
      summarise(value = value2[length(value2)])
    df3$variable <-rep("AC_Day_Energy_session", length(df3$timeUse))
    
    #Bind the 2 data frames and add date from the file name
    df2 <- rbind(df2, df3)
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    s4 <- rbind(s4, df)
  }
}
s4$id <- rep("Nur1C_S1", length(s4$value))

s5 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 2A S1/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption (vRELAY1_LVL in W) and cumulative energy (AC_Day_Energy_session in Wattmin)
    df_sub <- df[df$variable=="vRELAY1_LVL" | df$variable=="AC_Day_Energy_session", ]
    df_sub$value <- as.numeric(df_sub$value)
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for instantaneous power
    df2 <- df_sub[df_sub$variable=="vRELAY1_LVL",] %>%
      group_by(timeUse) %>%
      summarise(value = mean(value))
    df2$variable <-rep("vRELAY1_LVL", length(df2$timeUse))
    
    #Correct cumulative total energy if not reset
    df3_sub <- df_sub[df_sub$variable=="AC_Day_Energy_session", ]
    if(df3_sub$value[1]!=0) { #If value has not reset
      #find if and where the value has reset
      flag=FALSE
      for(l in 2:length(df3_sub$timestamp)) {
        if(flag==FALSE & df3_sub$value[l] < df3_sub$value[l-1]) {
          flag=TRUE
          index <- l
        }
      }
      if(flag==FALSE) { #Means the value never reset to 0
        #Subtract value at 0th index from all values
        df3_sub$value2 <- df3_sub$value - df3_sub$value[1]
      } else {
        df3_sub$value2 <- df3_sub$value
        df3_sub$value2[1:(index-1)] <- (df3_sub$value[1:(index-1)] - df3_sub$value[1])
        df3_sub$value2[index:length(df3_sub$timestamp)] <- 
          df3_sub$value[index:length(df3_sub$timestamp)] + df3_sub$value2[index-1]
      }
    } else {
      df3_sub$value2 <- df3_sub$value
    }
    
    #Extract cumulative total energy per hour
    df3 <- df3_sub %>%
      group_by(timeUse) %>%
      summarise(value = value2[length(value2)])
    df3$variable <-rep("AC_Day_Energy_session", length(df3$timeUse))
    
    #Bind the 2 data frames and add date from the file name
    df2 <- rbind(df2, df3)
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    s5 <- rbind(s5, df)
  }
}
s5$id <- rep("Nur2A_S1", length(s5$value))

s6 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 2A S2/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption (vRELAY1_LVL in W) and cumulative energy (AC_Day_Energy_session in Wattmin)
    df_sub <- df[df$variable=="vRELAY1_LVL" | df$variable=="AC_Day_Energy_session", ]
    df_sub$value <- as.numeric(df_sub$value)
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for instantaneous power
    df2 <- df_sub[df_sub$variable=="vRELAY1_LVL",] %>%
      group_by(timeUse) %>%
      summarise(value = mean(value))
    df2$variable <-rep("vRELAY1_LVL", length(df2$timeUse))
    
    #Correct cumulative total energy if not reset
    df3_sub <- df_sub[df_sub$variable=="AC_Day_Energy_session", ]
    if(df3_sub$value[1]!=0) { #If value has not reset
      #find if and where the value has reset
      flag=FALSE
      for(l in 2:length(df3_sub$timestamp)) {
        if(flag==FALSE & df3_sub$value[l] < df3_sub$value[l-1]) {
          flag=TRUE
          index <- l
        }
      }
      if(flag==FALSE) { #Means the value never reset to 0
        #Subtract value at 0th index from all values
        df3_sub$value2 <- df3_sub$value - df3_sub$value[1]
      } else {
        df3_sub$value2 <- df3_sub$value
        df3_sub$value2[1:(index-1)] <- (df3_sub$value[1:(index-1)] - df3_sub$value[1])
        df3_sub$value2[index:length(df3_sub$timestamp)] <- 
          df3_sub$value[index:length(df3_sub$timestamp)] + df3_sub$value2[index-1]
      }
    } else {
      df3_sub$value2 <- df3_sub$value
    }
    
    #Extract cumulative total energy per hour
    df3 <- df3_sub %>%
      group_by(timeUse) %>%
      summarise(value = value2[length(value2)])
    df3$variable <-rep("AC_Day_Energy_session", length(df3$timeUse))
    
    #Bind the 2 data frames and add date from the file name
    df2 <- rbind(df2, df3)
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    s6 <- rbind(s6, df)
  }
}
s6$id <- rep("Nur2A_S2", length(s6$value))

s7 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 2B S1/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption (vRELAY1_LVL in W) and cumulative energy (AC_Day_Energy_session in Wattmin)
    df_sub <- df[df$variable=="vRELAY1_LVL" | df$variable=="AC_Day_Energy_session", ]
    df_sub$value <- as.numeric(df_sub$value)
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for instantaneous power
    df2 <- df_sub[df_sub$variable=="vRELAY1_LVL",] %>%
      group_by(timeUse) %>%
      summarise(value = mean(value))
    df2$variable <-rep("vRELAY1_LVL", length(df2$timeUse))
    
    #Correct cumulative total energy if not reset
    df3_sub <- df_sub[df_sub$variable=="AC_Day_Energy_session", ]
    if(df3_sub$value[1]!=0) { #If value has not reset
      #find if and where the value has reset
      flag=FALSE
      for(l in 2:length(df3_sub$timestamp)) {
        if(flag==FALSE & df3_sub$value[l] < df3_sub$value[l-1]) {
          flag=TRUE
          index <- l
        }
      }
      if(flag==FALSE) { #Means the value never reset to 0
        #Subtract value at 0th index from all values
        df3_sub$value2 <- df3_sub$value - df3_sub$value[1]
      } else {
        df3_sub$value2 <- df3_sub$value
        df3_sub$value2[1:(index-1)] <- (df3_sub$value[1:(index-1)] - df3_sub$value[1])
        df3_sub$value2[index:length(df3_sub$timestamp)] <- 
          df3_sub$value[index:length(df3_sub$timestamp)] + df3_sub$value2[index-1]
      }
    } else {
      df3_sub$value2 <- df3_sub$value
    }
    
    #Extract cumulative total energy per hour
    df3 <- df3_sub %>%
      group_by(timeUse) %>%
      summarise(value = value2[length(value2)])
    df3$variable <-rep("AC_Day_Energy_session", length(df3$timeUse))
    
    #Bind the 2 data frames and add date from the file name
    df2 <- rbind(df2, df3)
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    s7 <- rbind(s7, df)
  }
}
s7$id <- rep("Nur2B_S1", length(s7$value))

s8 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Nur 2C S1/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption (vRELAY1_LVL in W) and cumulative energy (AC_Day_Energy_session in Wattmin)
    df_sub <- df[df$variable=="vRELAY1_LVL" | df$variable=="AC_Day_Energy_session", ]
    df_sub$value <- as.numeric(df_sub$value)
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for instantaneous power
    df2 <- df_sub[df_sub$variable=="vRELAY1_LVL",] %>%
      group_by(timeUse) %>%
      summarise(value = mean(value))
    df2$variable <-rep("vRELAY1_LVL", length(df2$timeUse))
    
    #Correct cumulative total energy if not reset
    df3_sub <- df_sub[df_sub$variable=="AC_Day_Energy_session", ]
    if(df3_sub$value[1]!=0) { #If value has not reset
      #find if and where the value has reset
      flag=FALSE
      for(l in 2:length(df3_sub$timestamp)) {
        if(flag==FALSE & df3_sub$value[l] < df3_sub$value[l-1]) {
          flag=TRUE
          index <- l
        }
      }
      if(flag==FALSE) { #Means the value never reset to 0
        #Subtract value at 0th index from all values
        df3_sub$value2 <- df3_sub$value - df3_sub$value[1]
      } else {
        df3_sub$value2 <- df3_sub$value
        df3_sub$value2[1:(index-1)] <- (df3_sub$value[1:(index-1)] - df3_sub$value[1])
        df3_sub$value2[index:length(df3_sub$timestamp)] <- 
          df3_sub$value[index:length(df3_sub$timestamp)] + df3_sub$value2[index-1]
      }
    } else {
      df3_sub$value2 <- df3_sub$value
    }
    
    #Extract cumulative total energy per hour
    df3 <- df3_sub %>%
      group_by(timeUse) %>%
      summarise(value = value2[length(value2)])
    df3$variable <-rep("AC_Day_Energy_session", length(df3$timeUse))
    
    #Bind the 2 data frames and add date from the file name
    df2 <- rbind(df2, df3)
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    s8 <- rbind(s8, df)
  }
}
s8$id <- rep("Nur2C_S1", length(s8$value))

s9 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Playground S1/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption (vRELAY1_LVL in W) and cumulative energy (AC_Day_Energy_session in Wattmin)
    df_sub <- df[df$variable=="vRELAY1_LVL" | df$variable=="AC_Day_Energy_session", ]
    df_sub$value <- as.numeric(df_sub$value)
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for instantaneous power
    df2 <- df_sub[df_sub$variable=="vRELAY1_LVL",] %>%
      group_by(timeUse) %>%
      summarise(value = mean(value))
    df2$variable <-rep("vRELAY1_LVL", length(df2$timeUse))
    
    #Correct cumulative total energy if not reset
    df3_sub <- df_sub[df_sub$variable=="AC_Day_Energy_session", ]
    if(df3_sub$value[1]!=0) { #If value has not reset
      #find if and where the value has reset
      flag=FALSE
      for(l in 2:length(df3_sub$timestamp)) {
        if(flag==FALSE & df3_sub$value[l] < df3_sub$value[l-1]) {
          flag=TRUE
          index <- l
        }
      }
      if(flag==FALSE) { #Means the value never reset to 0
        #Subtract value at 0th index from all values
        df3_sub$value2 <- df3_sub$value - df3_sub$value[1]
      } else {
        df3_sub$value2 <- df3_sub$value
        df3_sub$value2[1:(index-1)] <- (df3_sub$value[1:(index-1)] - df3_sub$value[1])
        df3_sub$value2[index:length(df3_sub$timestamp)] <- 
          df3_sub$value[index:length(df3_sub$timestamp)] + df3_sub$value2[index-1]
      }
    } else {
      df3_sub$value2 <- df3_sub$value
    }
    
    #Extract cumulative total energy per hour
    df3 <- df3_sub %>%
      group_by(timeUse) %>%
      summarise(value = value2[length(value2)])
    df3$variable <-rep("AC_Day_Energy_session", length(df3$timeUse))
    
    #Bind the 2 data frames and add date from the file name
    df2 <- rbind(df2, df3)
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    s9 <- rbind(s9, df)
  }
}
s9$id <- rep("PG_S1", length(s9$value))

s10 <- data.frame()
for(j in 1:1) {
  if(j==1) {
    setwd("~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/Playground S2/08 2019/")
  } 
  file_list <- list.files()
  for(i in 1:length(file_list)) {
    df <- read.csv(file_list[i], header = FALSE, quote = "\"", skipNul = TRUE)
    colnames(df) <- c("timestamp", "variable", "value")
    df$value <- as.character(df$value)
    df$variable <- as.character(df$variable)
    
    #Separate the power consumption (vRELAY1_LVL in W) and cumulative energy (AC_Day_Energy_session in Wattmin)
    df_sub <- df[df$variable=="vRELAY1_LVL" | df$variable=="AC_Day_Energy_session", ]
    df_sub$value <- as.numeric(df_sub$value)
    
    #Add time - we need to extract hours to get hourly means
    df_sub$time <- as.POSIXct(df_sub$timestamp, tz="GMT", origin="1970-01-01")
    df_sub$timeUse <- format(df_sub$time, format='%H')
    
    #Extract hourly means for instantaneous power
    df2 <- df_sub[df_sub$variable=="vRELAY1_LVL",] %>%
      group_by(timeUse) %>%
      summarise(value = mean(value))
    df2$variable <-rep("vRELAY1_LVL", length(df2$timeUse))
    
    #Correct cumulative total energy if not reset
    df3_sub <- df_sub[df_sub$variable=="AC_Day_Energy_session", ]
    if(df3_sub$value[1]!=0) { #If value has not reset
      #find if and where the value has reset
      flag=FALSE
      for(l in 2:length(df3_sub$timestamp)) {
        if(flag==FALSE & df3_sub$value[l] < df3_sub$value[l-1]) {
          flag=TRUE
          index <- l
        }
      }
      if(flag==FALSE) { #Means the value never reset to 0
        #Subtract value at 0th index from all values
        df3_sub$value2 <- df3_sub$value - df3_sub$value[1]
      } else {
        df3_sub$value2 <- df3_sub$value
        df3_sub$value2[1:(index-1)] <- (df3_sub$value[1:(index-1)] - df3_sub$value[1])
        df3_sub$value2[index:length(df3_sub$timestamp)] <- 
          df3_sub$value[index:length(df3_sub$timestamp)] + df3_sub$value2[index-1]
      }
    } else {
      df3_sub$value2 <- df3_sub$value
    }
    
    #Extract cumulative total energy per hour
    df3 <- df3_sub %>%
      group_by(timeUse) %>%
      summarise(value = value2[length(value2)])
    df3$variable <-rep("AC_Day_Energy_session", length(df3$timeUse))
    
    #Bind the 2 data frames and add date from the file name
    df2 <- rbind(df2, df3)
    df2$date <- as.Date((rep(gsub("\\..*","",file_list[i]), length(df2$value))),
                        format = "%d-%m-%Y")
    
    #Create a data frame with the above values and bind to a complete df 
    df <- data.frame(date=df2$date, hour=df2$timeUse, 
                     variable=df2$variable, value=df2$value)
    df$hour <- as.character(df$hour)
    df$variable <- as.character(df$variable)
    s10 <- rbind(s10, df)
  }
}
s10$id <- rep("PG_S2", length(s10$value))
```
```{r, echo=FALSE}
#Combining all CPEs
cpe_all <- data.frame()
cpe_all <- rbind(cpe_all, cpe1, cpe2, cpe3, cpe4, cpe5, cpe6, cpe7, cpe8, cpe9,
                 cpe10, cpe11, cpe12, cpe13, cpe14, cpe15, cpe16, cpe17, cpe18,
                 cpe19, cpe20)
cpe_all <- cpe_all[order(cpe_all$date),]

#Combining all 10 sockets
s_all <- data.frame()
s_all <- rbind(s_all, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10)
s_all <- s_all[order(s_all$date),]
```

```{r, echo=FALSE, include = FALSE}
#Extract hourly means for AC Consumption L1 (W), PV Power (W), State of charge (%), Discharged Energy (kWh), Charged Energy (kWh) for system data

#One file under full data from June to Nov - Rwanda time zone
filename <- "~/OneDrive - Coventry University/HEED_analysis/Micro-grid/Data/System Data/Full data/HEEDKigemeMicroGrid_20190531-2200_to_20191113-2100.csv"

#Concatenate the headers spread across first 3 rows
headers <- read_csv(filename, col_names = FALSE, na="..", n_max = 3)
#Replace NA in header with "" for missing row 3 values
headers[is.na(headers)] <- ""
column_labels <- headers %>% summarize_all(str_c, collapse = " ")
headers = unname(unlist(column_labels[1,]))

#Read data without the first three rows
system_data <- read_csv(filename, col_names = headers, na="..", skip = 3)

#Replace NA in data frame with "" for missing values as in raw file
system_data[is.na(system_data)] <- ""

#Extract the columns we require
#Extract system overview data for AC Consumption L1 - W
#Find all column names with System overview
columns <- headers[which(grepl("System overview", headers, fixed=TRUE))]
#Find all column names with AC Consumption L1
colNames <- columns[which(grepl("AC Consumption L1", columns, fixed=TRUE))]
colNames <- c(headers[1], colNames) 
sysOverview <- system_data[,colNames]

#Extract Solar Charger data to get PV power - W
#Find all column names with Solar Charger
columns <- headers[which(grepl("Solar Charger", headers, fixed=TRUE))]
#Find all column names with PV power
colNames <- columns[which(grepl("PV power", columns, fixed=TRUE))]
colNames <- c(headers[1], colNames) 
solarCharger <- system_data[,colNames]

#Extract Battery Monitor data to get State of charge (%), Discharged Energy(kWh), Charged Energy(kWh)
#Find all column names with Solar Charger
columns <- headers[which(grepl("Battery Monitor", headers, fixed=TRUE))]
#Find all column names with State of charge
colNames <- columns[which(grepl("State of charge", columns, fixed=TRUE))]
#Find all column names with Discharged Energy
colNames <- c(colNames, columns[which(grepl("Discharged Energy", columns, fixed=TRUE))])
#Find all column names with Charged Energy
colNames <- c(colNames, columns[which(grepl("Charged Energy", columns, fixed=TRUE))])
colNames <- c(headers[1], colNames) 
batteryMonitor <- system_data[,colNames]

systemData <- data.frame()
systemData <- cbind(sysOverview, solarCharger[,-1], batteryMonitor[,-1])
systemData$`System overview [0] AC Consumption L1 W` <- 
  as.numeric(systemData$`System overview [0] AC Consumption L1 W`)
systemData$`Solar Charger [260] PV power ` <- 
  as.numeric(systemData$`Solar Charger [260] PV power `)
systemData$`Battery Monitor [258] Discharged Energy kWh` <- 
  as.numeric(systemData$`Battery Monitor [258] Discharged Energy kWh`)
systemData$`Battery Monitor [258] Charged Energy kWh` <- 
  as.numeric(systemData$`Battery Monitor [258] Charged Energy kWh`) 
```

```{r, echo=FALSE, include = FALSE}
#Reading in weather data - hourly values
filename <- "~/OneDrive - Coventry University/HEED_analysis/Hall/Weather data/weather_data.xlsx"
headers <- read_excel(filename, col_names = FALSE, na="..", n_max = 2)
#Replace NA in header with "" for missing row 3 values
headers[is.na(headers)] <- ""
column_labels <- headers %>% summarize_all(str_c, collapse = " ")
headers = unname(unlist(column_labels[1,]))
weather_data <- read_excel(filename, col_names = headers, na="..", skip = 2,
                           col_types=c("date","numeric","numeric"))
#Replace NA in data frame with "" for missing values as in raw file
weather_data[is.na(weather_data)] <- ""
#Data is 12 years behind - change year to 2019
year(weather_data$`Time (2019!) `) <- 2019
```
